import psycopg2
import random
conexion1 = psycopg2.connect(user = "postgres",
                                 password = "12345678",
                                  host = "localhost",
                                  port = "8081",
                                  database = "sistema_votacion")

Amazonas=["CHACHAPOYAS","ASUNCION","BALSAS","CHETO","CHILIQUIN","CHUQUIBAMBA","GRANADA","HUANCAS","LA JALCA","LEIMEBAMBA","LEVANTO",
"MAGDALENA","MARISCAL CASTILLA","MOLINOPAMPA","MONTEVIDEO","OLLEROS","QUINJALCA","SAN FRANCISCO DE DAGUAS","SAN ISIDRO DE MAINO","SOLOCO",
"SONCHE","LA PECA","ARAMANGO","COPALLIN"]

Ancash=["HUARAZ","INDEPENDENCIA","COCHABAMBA","COLCABAMBA","HUANCHAY","JANGAS","LA LIBERTAD","OLLEROS","PAMPAS GRANDE","PARIACOTO",
"PIRA","TARICA","AIJA","CORIS","HUACLLAN","LA MERCED","SUCCHA","CHIQUIAN","ABELARDO PARDO LEZAMETA","AQUIA","CAJACAY","HUAYLLACAYAN",
"HUASTA","MANGAS"]

Apurimac=["ABANCAY","CIRCA","CURAHUASI","CHACOCHE","HUANIPACA","LAMBRAMA","PICHIRHUA","SAN PEDRO DE CACHORA","TAMBURCO",
"CHALHUANCA","CAPAYA","CARAYBAMBA","COLCABAMBA","COTARUSE","CHAPIMARCA","HUAYLLO","LUCRE","POCOHUANCA","SAÑAYCA",
"SORAYA","TAPAIRIHUA","TINTAY","TORAYA","YANACA"]

Arequipa=["AREQUIPA","CAYMA","CERRO COLORADO","CHARACATO","CHIGUATA","LA JOYA","MIRAFLORES","MOLLEBAYA","PAUCARPATA","POCSI",
"POLOBAYA","QUEQUEÑA","SABANDIA","SACHACA","SAN JUAN DE SIGUAS","SAN JUAN DE TARUCANI","SANTA ISABEL DE SIGUAS",
"SANTA RITA DE SIHUAS","SOCABAYA","TIABAYA","UCHUMAYO","VITOR","YANAHUARA","YARABAMBA","Mariano Melgar"]

Ayacucho=["AYACUCHO","ACOS VINCHOS","CARMEN ALTO","CHIARA","QUINUA","SAN JOSE DE TICLLAS","SAN JUAN BAUTISTA",
"SANTIAGO DE PISCHA","VINCHOS","TAMBILLO","ACOCRO","SOCOS","OCROS","PACAYCASA","JESUS NAZARENO","CANGALLO","CHUSCHI","LOS MOROCHUCOS",
"PARAS","TOTOS","MARIA PARADO DE BELLIDO","HUANTA","AYAHUANCO","HUAMANGU"]

CajaMarca=["CAJAMARCA","ASUNCION","COSPAN","CHETILLA","ENCAÑADA","JESUS","LOS BAÑOS DEL INCA","LLACANORA","MAGDALENA","MATARA",
"NAMORA","SAN JUAN","CAJABAMBA","CACHACHI","CONDEBAMBA","SITACOCHA","CELENDIN","CORTEGANA","CHUMUCH","HUASMIN","JORGE CHAVEZ",
"JOSE GALVEZ","MIGUEL IGLESIAS","OXAMAR"]

Cusco=["CUSCO","CCORCA","POROY","SAN JERONIMO","SAN SEBASTIAN","SANTIAGO","SAYLLA","WANCHAQ","ACOMAYO","ACOPIA","ACOS","POMACANCHI",
"RONDOCAN","SANGARARA","MOSOC LLACTA","ANTA","CHINCHAYPUJIO","HUAROCONDO","LIMATAMBO","MOLLEPATA","PUCYURA","ZURITE","CACHIMAYO",
"ANCAHUAS"]

Huancavelica=["HUANCAVELICA","ACOBAMBILLA","ACORIA","CONAYCA","CUENCA","HUACHOCOLPA","HUAYLLAHUARA","IZCUCHACA","LARIA","MANTA",
"MARISCAL CACERES","MOYA","NUEVO OCCORO","PALCA","PILCHACA","VILCA","YAULI","ASCENSION","HUANDO","ACOBAMBA","ANTA","ANDABAMBA",
"CAJA","MARCAS"]

Huanuco=["HUANUCO","CHINCHAO","CHURUBAMBA","MARGOS","QUISQUI","SAN FRANCISCO DE CAYRAN","SAN PEDRO DE CHAULAN","SANTA MARIA DEL VALLE",
"YARUMAYO","AMARILIS","PILLCO MARCA","YACUS","AMBO","CAYNA","COLPAS","CONCHAMARCA","HUACAR","SAN FRANCISCO","SAN RAFAEL","TOMAY-KICHWA",
"LA UNION","CHUQUIS","MARIAS","PACHAS"]

Ica=["ICA","LA TINGUIÑA","LOS AQUIJES","PARCONA","PUEBLO NUEVO","SALAS","SAN JOSE DE LOS MOLINOS","SAN JUAN BAUTISTA","SANTIAGO",
"SUBTANJALLA","YAUCA DEL ROSARIO","TATE","PACHACUTEC","OCUCAJE","CHINCHA ALTA","CHAVIN","CHINCHA BAJA","EL CARMEN","GROCIO PRADO",
"SAN PEDRO DE HUACARPANA","SUNAMPE","TAMBO DE MORA","ALTO LARAN","PUEBLO"]

Junin=["HUANCAYO","CARHUACALLANGA","COLCA","CULLHUAS","CHACAPAMPA","CHICCHE","CHILCA","CHONGOS ALTO","CHUPURO","EL TAMBO",
"HUACRAPUQUIO","HUALHUAS","HUANCAN","HUASICANCHA","HUAYUCACHI","INGENIO","PARIAHUANCA","PILCOMAYO","PUCARA","QUICHUAY",
"QUILCAS","SAN AGUSTIN","SAN JERONIMO DE TUNAN","SANTO DOMINGO"]

LaLibertad=["TRUJILLO","HUANCHACO","LAREDO","MOCHE","SALAVERRY","SIMBAL","VICTOR LARCO HERRERA","POROTO","EL PORVENIR",
"LA ESPERANZA","FLORENCIA DE MORA","BOLIVAR","BAMBAMARCA","CONDORMARCA","LONGOTEA","UCUNCHA","UCHUMARCA","HUAMACHUCO",
"COCHORCO","CURGOS","CHUGAY","MARCABAL","SANAGORAN","SARIN"]

Lambayque=["CHICLAYO","CHONGOYAPE","ETEN","ETEN PUERTO","LAGUNAS","MONSEFU","NUEVA ARICA","OYOTUN","PICSI","PIMENTEL",
"REQUE","JOSE LEONARDO ORTIZ","SANTA ROSA","SAÑA","LA VICTORIA","CAYALTI","PATAPO","POMALCA","PUCALA","TUMAN","FERREÑAFE",
"INCAHUASI","CAÑARIS","Pueblo Nuevo"]

Lima=["LIMA","ANCON","ATE","BREÑA","CARABAYLLO","COMAS","CHACLACAYO","CHORRILLOS","LA VICTORIA","LA MOLINA","LINCE",
"LURIGANCHO","LURIN","MAGDALENA DEL MAR","MIRAFLORES","PACHACAMAC","PUEBLO LIBRE","PUCUSANA","PUENTE PIEDRA","PUNTA HERMOSA",
"PUNTA NEGRA","RIMAC","SAN BARTOLO","SAN ISIDRO"]

Loreto=["IQUITOS","ALTO NANAY","FERNANDO LORES","LAS AMAZONAS","MAZAN","NAPO","PUTUMAYO","TORRES CAUSANA","INDIANA",
"PUNCHANA","BELEN","SAN JUAN BAUTISTA","TENIENTE MANUEL CLAVERO","YURIMAGUAS","BALSAPUERTO","JEBEROS","LAGUNAS","SANTA CRUZ",
"TENIENTE CESAR LOPEZ ROJAS","NAUTA","PARINARI","TIGRE","URARINAS","TROMPETE"]

MadreDeDios=["TAMBOPATA","INAMBARI","LAS PIEDRAS","LABERINTO","MANU","FITZCARRALD","MADRE DE DIOS","HUEPETUHE","IÑAPARI",
"IBERIA","TAHUAMANU"]

Moquegua=["MOQUEGUA","CARUMAS","CUCHUMBAYA","SAN CRISTOBAL","TORATA","SAMEGUA","OMATE","COALAQUE","CHOJATA","ICHUÑA","LA CAPILLA",
"LLOQUE","MATALAQUE","PUQUINA","QUINISTAQUILLAS","UBINAS","YUNGA","ILO","EL ALGARROBAL","PACOCHA"]

Pasco=["CHAUPIMARCA","HUACHON","HUARIACA","HUAYLLAY","NINACACA","PALLANCHACRA","PAUCARTAMBO","SAN FCO DE ASIS DE YARUSYACAN",
"SIMON BOLIVAR","TICLACAYAN","TINYAHUARCO","VICCO","YANACANCHA","YANAHUANCA","CHACAYAN","GOYLLARISQUIZGA","PAUCAR",
"SAN PEDRO DE PILLAO","SANTA ANA DE TUSI","TAPUC","VILCABAMBA","OXAPAMPA","CHONTABAMBA","HUANCABAMBA","PUERTO BERMUDEZ",
"VILLA RICA","POZUZO","PALCAZU","CONSTITUCION"]

Piura=["PIURA","CASTILLA","CATACAOS","LA ARENA","LA UNION","LAS LOMAS","TAMBO GRANDE","CURA MORI","EL TALLAN","AYABACA",
"FRIAS","LAGUNAS","MONTERO","PACAIPAMPA","SAPILLICA","SICCHEZ","SUYO","JILILI","PAIMAS","HUANCABAMBA","CANCHAQUE","HUARMACA",
"SONDOR","SONDORIL"]

Puno=["PUNO","ACORA","ATUNCOLLA","CAPACHICA","COATA","CHUCUITO","HUATA","MAÑAZO","PAUCARCOLLA","PICHACANI","SAN ANTONIO","TIQUILLACA",
"VILQUE","PLATERIA","AMANTANI","AZANGARO","ACHAYA","ARAPA","ASILLO","CAMINACA","CHUPA","JOSE DOMINGO CHOQUEHUANCA","MUÑANI","POTONI"]

SanMartin=["MOYOBAMBA","CALZADA","HABANA","JEPELACIO","SORITOR","YANTALO","SAPOSOA","PISCOYACU","SACANCHE","TINGO DE SAPOSOA",
"ALTO SAPOSOA","EL ESLABON","LAMAS","BARRANQUITA","CAYNARACHI","CUÑUMBUQUI","PINTO RECODO","RUMISAPA","SHANAO","TABALOSOS",
"ZAPATERO","ALONSO DE ALVARADO","SAN ROQUE DE CUMBAZA","JUANJUI"]

Tacna=["TACNA","CALANA","INCLAN","PACHIA","PALCA","POCOLLAY","SAMA","ALTO DE LA ALIANZA","CIUDAD NUEVA",
"CORONEL GREGORIO ALBARRACIN L.","TARATA","HEROES ALBARRACIN","ESTIQUE","ESTIQUE PAMPA","SITAJARA","SUSAPAYA",
"TARUCACHI","TICACO","LOCUMBA","ITE","ILABAYA","CANDARAVE","CAIRANI","CURIBAYA","HUANUARA","QUILAHUANI","CAMILACA"]

Tumbes=["TUMBES","CORRALES","LA CRUZ","PAMPAS DE HOSPITAL","SAN JACINTO","SAN JUAN DE LA VIRGEN","ZORRITOS","CASITAS",
"CANOAS DE PUNTA SAL","ZARUMILLA","MATAPALO","PAPAYAL","AGUAS VERDES"]

Ucayali=["CALLERIA","YARINACOCHA","MASISEA","CAMPOVERDE","IPARIA","NUEVA REQUENA","MANANTAY","PADRE ABAD","IRAZOLA",
"CURIMANA","RAIMONDI","TAHUANIA","YURUA","SEPAHUA","PURUS"]

ciudades=[Amazonas,Ancash,Apurimac,Arequipa,Ayacucho,CajaMarca,Cusco,Huancavelica,Huanuco,Ica,Junin,LaLibertad,Lambayque,
Lima,Loreto,MadreDeDios,Moquegua,Pasco,Ica,Junin,LaLibertad,Lambayque,Lima,Loreto,MadreDeDios,Moquegua,Pasco]

ciudades_aux=["Amazonas","Ancash","Apurimac","Arequipa","Ayacucho","CajaMarca","Cusco","Huancavelica","Huanuco","Ica","Junin",
"LaLibertad","Lambayque","Lima","Loreto","MadreDeDios","Moquegua","Pasco","Ica","Junin","LaLibertad","Lambayque","Lima",
"Loreto","MadreDeDios","Moquegua","Pasco"]
id=0
for i in range(len(ciudades)):
    for j in range(len(ciudades[i])):
        cursor1=conexion1.cursor()
        sql="insert into ubigeo(idubigeo,ubigeo_distrito,ubigeo_ciudad,ubigeo_pais) values (%s,%s,%s,%s)"
        datos=(id,ciudades[i][j],ciudades_aux[i],"Peru")
        id=id+1
        cursor1.execute(sql,datos)
        conexion1.commit()
conexion1.close()

#=CARACTER(34)&A1&CARACTER(34)&CARACTER(44)